name: rikulo_commons
version: 4.3.1
description: Common reusable Dart classes and utilities.
homepage: http://rikulo.org
repository: https://github.com/rikulo/commons
issue_tracker: https://github.com/rikulo/commons/issues

dependencies:
  logging: any
  mime: any
  charcode: any

dev_dependencies:
  test: any

environment:
  sdk: '>=2.8.0 <3.0.0'
