name: rikulo_commons
version: 6.1.0+1
description: Collections of common reusable classes and utilities for Dart language.
homepage: https://github.com/rikulo/commons
repository: https://github.com/rikulo/commons
issue_tracker: https://github.com/rikulo/commons/issues

dependencies:
  logging: any
  mime: any
  charcode: any

dev_dependencies:
  test: any

environment:
  sdk: '>=3.0.0 <4.0.0'
